-- Binocolo OpenAPI.it Company legal forms lookup.
-- Target database: Anisetta PostgreSQL.
-- Source data: apps/binocolo/docs/detailed_legal_forms.json.

BEGIN;

CREATE SCHEMA IF NOT EXISTS binocolo;

CREATE TABLE IF NOT EXISTS binocolo.company_legal_forms (
  sort_order      integer NOT NULL,
  code            text PRIMARY KEY,
  description_it  text NOT NULL,
  description_en  text NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT company_legal_forms_sort_order_positive CHECK (sort_order > 0),
  CONSTRAINT company_legal_forms_code_check CHECK (code ~ '^[A-Z]{2}$'),
  CONSTRAINT company_legal_forms_description_it_not_blank CHECK (btrim(description_it) <> ''),
  CONSTRAINT company_legal_forms_description_en_not_blank CHECK (btrim(description_en) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS company_legal_forms_sort_order_unique
  ON binocolo.company_legal_forms (sort_order);

INSERT INTO binocolo.company_legal_forms (
  sort_order,
  code,
  description_it,
  description_en
)
VALUES
  (1, $$AA$$, $$SOCIETA' IN ACCOMANDITA PER AZIONI$$, $$LIMITED PARTNERSHIP$$),
  (2, $$AC$$, $$ASSOCIAZIONE$$, $$ASSOCIATION$$),
  (3, $$AE$$, $$SOCIETA' CONSORTILE IN ACCOMANDITA SEMPLICE$$, $$SIMPLE PARTNERSHIP CONSORTIUM$$),
  (4, $$AF$$, $$ALTRE FORME$$, $$OTHER FORMS$$),
  (5, $$AI$$, $$ASSOCIAZIONE IMPRESA$$, $$BUSINESS ASSOCIATION$$),
  (6, $$AL$$, $$AZIENDA SPECIALE DI ENTE LOCALE$$, $$LOCAL AUTHORITY SPECIAL COMPANY$$),
  (7, $$AM$$, $$AZIENDA MUNICIPALE$$, $$MUNICIPAL COMPANY$$),
  (8, $$AN$$, $$SOCIETA' CONSORTILE IN NOME COLLETTIVO$$, $$CONSORTIUM IN COLLECTIVE NAME/ GENERAL CONSORTIUM PARTNERSHIP$$),
  (9, $$AP$$, $$AZIENDA PROVINCIALE$$, $$PROVINCIAL COMPANY$$),
  (10, $$AR$$, $$AZIENDA REGIONALE$$, $$REGIONAL COMPANY$$),
  (11, $$AS$$, $$SOCIETA' IN ACCOMANDITA SEMPLICE$$, $$SIMPLE LIMITED PARTNERSHIP$$),
  (12, $$AT$$, $$AZIENDA AUTONOMA STATALE$$, $$AUTONOMOUS STATE COMPANY$$),
  (13, $$AU$$, $$SOCIETA' PER AZIONI CON SOCIO UNICO$$, $$LIMITED COMPANY WITH ONE SHAREHOLDER$$),
  (14, $$AZ$$, $$AZIENDA SPECIALE$$, $$SPECIAL COMPANY$$),
  (15, $$CC$$, $$CONSORZIO CON ATTIVITA' ESTERNA$$, $$CONSORTIUM WITH EXTERNAL ACTIVITIES$$),
  (16, $$CE$$, $$COMUNIONE EREDITARIA$$, $$JOINT HEIRS$$),
  (17, $$CF$$, $$CONSORZIO FIDI$$, $$CONSORTIUM IN THE CREDIT SECTOR$$),
  (18, $$CI$$, $$SOCIETA' COOPERATIVA A RESPONSABILITA ILLIMITATA$$, $$UNLIMITED MUTUAL COMPANY$$),
  (19, $$CL$$, $$SOCIETA' COOPERATIVA A RESPONSABILITA LIMITATA$$, $$LIMITED MUTUAL COMPANY$$),
  (20, $$CM$$, $$CONSORZIO MUNICIPALE$$, $$MUNICIPAL CONSORTIUM$$),
  (21, $$CN$$, $$SOCIETA' CONSORTILE$$, $$CONSORTIUM COMPANY$$),
  (22, $$CO$$, $$CONSORZIO$$, $$CONSORTIUM$$),
  (23, $$CR$$, $$CONSORZIO INTERCOMUNALE$$, $$INTERCOMMUNAL CONSORTIUM$$),
  (24, $$CS$$, $$CONSORZIO SENZA ATTIVITA' ESTERNA$$, $$CONSORTIUM WITHOUT EXTERNAL ACTIVITIES$$),
  (25, $$CZ$$, $$CONSORZIO DI CUI AL DLGS 267/2000$$, $$CONSORTIUM ACCORDING TO L.142/90$$),
  (26, $$DI$$, $$IMPRESA INDIVIDUALE$$, $$INDIVIDUAL BUSINESS$$),
  (27, $$EC$$, $$ENTE PUBBLICO COMMERCIALE$$, $$PUBLIC COMMERCIAL INSTITUTION/CORPORATION$$),
  (28, $$ED$$, $$ENTE DIRITTO PUBBLICO$$, $$PUBLIC INSTITUTION/CORPORATION$$),
  (29, $$EE$$, $$ENTE ECCLESIASTICO$$, $$CHURCH INSTITUTION/CORPORATION$$),
  (30, $$EI$$, $$ENTE IMPRESA$$, $$BUSINESS CORPORATION/COMPANY/AUTHORITY$$),
  (31, $$EL$$, $$ENTE SOCIALE$$, $$SOCIAL INSTITUTION$$),
  (32, $$EM$$, $$ENTE MORALE$$, $$INSTITUTION/CORPORATION$$),
  (33, $$EN$$, $$ENTE$$, $$CORPORATION/COMPANY/AUTHORITY$$),
  (34, $$EP$$, $$ENTE PUBBLICO ECONOMICO$$, $$PUBLIC BODY$$),
  (35, $$ER$$, $$ENTE ECCLESIASTICO CIVILMENTE RICONOSCIUTO$$, $$CHURCH INSTITUTION/CORPORATION RECOGNISED UNDER CIVIL LAW$$),
  (36, $$ES$$, $$ENTE DI CUI ALLA L.R. 21-12-93, N.88$$, $$CORPORATION/COMPANY/AUTHORITY ACCORDING TO L.R. 21-12-93, N.88$$),
  (37, $$FI$$, $$FONDAZIONE IMPRESA$$, $$BUSINESS START-UP$$),
  (38, $$FO$$, $$FONDAZIONE$$, $$START-UP/ FOUNDATION$$),
  (39, $$GE$$, $$GRUPPO EUROPEO DI INTERESSE ECONOMICO$$, $$EUROPEAN ECONOMIC INTEREST GROUP$$),
  (40, $$IC$$, $$ISTITUTO DI CREDITO$$, $$FINANCIAL SERVICES INSTITUTION$$),
  (41, $$ID$$, $$ISTITUTO DI CREDITO DI DIRITTO PUBBLICO$$, $$JOINT STOCK BUSINESS$$),
  (42, $$IF$$, $$IMPRESA FAMILIARE$$, $$FAMILY BUSINESS$$),
  (43, $$IR$$, $$ISTITUTO RELIGIOSO$$, $$RELIGIOUS INSTITUTION$$),
  (44, $$LL$$, $$AZIENDA SPECIALE DI CUI AL DLGS 267/2000$$, $$SPECIAL COMPANY ACCORDING TO L. 142/90$$),
  (45, $$MA$$, $$MUTUA ASSICURAZIONE$$, $$MUTUAL ASSURANCE$$),
  (46, $$OC$$, $$SOCIETA' COOPERATIVA CONSORTILE$$, $$MUTUAL CONSORTIUM$$),
  (47, $$OO$$, $$COOPERATIVA SOCIALE$$, $$SOCIAL MUTUAL$$),
  (48, $$OS$$, $$SOCIETA' CONSORTILE COOPERATIVA A RESPONSABILITA' LIMITATA$$, $$LIMITED MUTUAL CONSORTIUM$$),
  (49, $$PA$$, $$ASSOCIAZIONE IN PARTECIPAZIONE$$, $$SHAREHOLDING ASSOCIATION$$),
  (50, $$PC$$, $$PICCOLA SOCIETA' COOPERATIVA$$, $$SMALL MUTUAL COMPANY$$),
  (51, $$PF$$, $$PERSONA FISICA$$, $$NATURAL PERSON$$),
  (52, $$PS$$, $$PICCOLA SOCIETA' COOPERATIVA A RESPONSABILITA' LIMITATA$$, $$SMALL LIMITED MUTUAL COMPANY$$),
  (53, $$RC$$, $$CONTRATTO DI RETE DOTATO DI SOGGETTIVITA' GIURIDICA$$, $$NETWORK CONTRACT EQUIPPED WITH LEGAL SUBJECTIVITY$$),
  (54, $$RR$$, $$SOCIETA' A RESPONSABILITA' LIMITATA A CAPITALE RIDOTTO$$, $$LIMITED LIABILITY COMPANY/LIMITED COMPANY$$),
  (55, $$RS$$, $$SOCIETA' A RESPONSABILITA' LIMITATA SEMPLIFICATA$$, $$LIMITED LIABILITY COMPANY/LIMITED COMPANY$$),
  (56, $$SA$$, $$SOCIETA' ANONIMA$$, $$ANONYMOUS COMPANY$$),
  (57, $$SC$$, $$SOCIETA' COOPERATIVA$$, $$MUTUAL COMPANY LIMITED BY SHARES$$),
  (58, $$SD$$, $$SOCIETA' EUROPEA$$, $$EUROPEAN COMPANY$$),
  (59, $$SE$$, $$SOCIETA' SEMPLICE$$, $$SIMPLE COMPANY$$),
  (60, $$SF$$, $$SOCIETA' DI FATTO$$, $$DE FACTO COMPANY$$),
  (61, $$SG$$, $$SOCIETA' COOPERATIVA EUROPEA$$, $$EUROPEAN MUTUAL COMPANY LIMITED BY SHARES$$),
  (62, $$SI$$, $$SOCIETA' IRREGOLARE$$, $$IRREGULAR COMPANY$$),
  (63, $$SL$$, $$SOCIETA' CONSORTILE A RESPONSABILITA' LIMITATA$$, $$CONSORTIUM LIMITED BY SHARES$$),
  (64, $$SM$$, $$SOCIETA' DI MUTUO SOCCORSO$$, $$MUTUAL AID COMPANY$$),
  (65, $$SN$$, $$SOCIETA' IN NOME COLLETTIVO$$, $$COLLECTIVE NAME COMPANY/ GENERAL PARTNERSHIP$$),
  (66, $$SO$$, $$SOCIETA' CONSORTILE PER AZIONI$$, $$CONSORTIUM LIMITED BY SHARES$$),
  (67, $$SP$$, $$SOCIETA' PER AZIONI$$, $$LIMITED COMPANY$$),
  (68, $$SR$$, $$SOCIETA' A RESPONSABILITA' LIMITATA$$, $$Limited Liability Company/ LIMITED COMPANY$$),
  (69, $$SS$$, $$SOCIETA' COSTITUITA IN BASE A LEGGI DI ALTRO STATO$$, $$COMPANY FOUNDED ON THE BASIS OF THE LAWS OF ANOTHER STATE$$),
  (70, $$ST$$, $$SOGGETTO ESTERO$$, $$FOREIGN SUBJECT$$),
  (71, $$SU$$, $$SOCIETA' A RESPONSABILITA' LIMITATA CON UNICO SOCIO$$, $$LIMITED COMPANY WITH ONE SHAREHOLDER$$),
  (72, $$SV$$, $$SOCIETA' TRA PROFESSIONISTI$$, $$PROFESSIONAL COMPANY$$),
  (73, $$SZ$$, $$SOCIETA' NON PREVISTA DALLA LEGISLAZIONE ITALIANA$$, $$COMPANY NOT ENVISAGED BY ITALIAN LEGISLATION$$),
  (74, $$XX$$, $$NON PRECISATA$$, $$UNSPECIFIED$$)
ON CONFLICT (code) DO UPDATE
SET sort_order = EXCLUDED.sort_order,
    description_it = EXCLUDED.description_it,
    description_en = EXCLUDED.description_en,
    updated_at = now();

DROP TRIGGER IF EXISTS company_legal_forms_set_updated_at
  ON binocolo.company_legal_forms;
CREATE TRIGGER company_legal_forms_set_updated_at
BEFORE UPDATE ON binocolo.company_legal_forms
FOR EACH ROW
EXECUTE FUNCTION binocolo.set_updated_at();

COMMIT;
