services:
  mrsmith:
    image: mrsmith:preprod
    container_name: mrsmith-preprod
    pull_policy: never
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./.env.preprod
