apiVersion: v1
kind: ConfigMap
metadata:
  name: mrsmith-config
data:
  PORT: "8080"
  KEYCLOAK_ISSUER_URL: "https://keycloak.example.com/realms/mrsmith"
  KEYCLOAK_FRONTEND_URL: "https://keycloak.example.com"
  KEYCLOAK_FRONTEND_REALM: "mrsmith"
  KEYCLOAK_FRONTEND_CLIENT_ID: "mrsmith-portal"
  CORS_ORIGINS: "https://mrsmith.example.com"
  STATIC_DIR: "/static"
  RDA_QUOTE_THRESHOLD: "3000"
  SIMULATORI_VENDITA_IAAS_TEMPLATE_ID: "7229f811c77569a9ab09c7f71cd923a942e3d5d5aac1d26b98950a19beb2e920"
