apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mrsmith-grappa-dcim-artifacts
  labels:
    app: mrsmith
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
