import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  Box,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  GripVertical,
  Heading2,
  Heading3,
  Heading4,
  Palette,
  Highlighter,
  Info,
  Italic,
  Link2,
  List,
  ListOrdered,
  Loader2,
  Lock,
  Mail,
  MoreVertical,
  Package,
  Pencil,
  Phone,
  Plus,
  RemoveFormatting,
  Search,
  Server,
  Settings,
  Sparkles,
  Trash2,
  TriangleAlert,
  Underline,
  User,
  Wifi,
  X,
  XCircle,
  type LucideProps,
} from 'lucide-react';

const registry = {
  'align-center': AlignCenter,
  'align-left': AlignLeft,
  'align-right': AlignRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'bar-chart-2': BarChart2,
  box: Box,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  clock: Clock,
  cloud: Cloud,
  copy: Copy,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'file-text': FileText,
  filter: Filter,
  'grip-vertical': GripVertical,
  heading2: Heading2,
  heading3: Heading3,
  heading4: Heading4,
  palette: Palette,
  highlighter: Highlighter,
  info: Info,
  italic: Italic,
  link: Link2,
  list: List,
  'list-ordered': ListOrdered,
  loader: Loader2,
  lock: Lock,
  mail: Mail,
  'more-vertical': MoreVertical,
  package: Package,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  'remove-formatting': RemoveFormatting,
  search: Search,
  server: Server,
  settings: Settings,
  sparkles: Sparkles,
  trash: Trash2,
  'triangle-alert': TriangleAlert,
  underline: Underline,
  user: User,
  wifi: Wifi,
  x: X,
  'x-circle': XCircle,
} as const;

export type IconName = keyof typeof registry;

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName;
}

export function Icon({ name, size = 18, strokeWidth = 1.75, ...rest }: IconProps) {
  const Component = registry[name];
  return <Component size={size} strokeWidth={strokeWidth} aria-hidden="true" {...rest} />;
}
