CREATE TABLE `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cdlan_systemodv` int(30) NOT NULL DEFAULT 0,
  `cdlan_tipodoc` enum('TSC-ORDINE-RIC','TSC-ORDINE') NOT NULL,
  `cdlan_ndoc` varchar(20) DEFAULT NULL,
  `cdlan_datadoc` varchar(10) DEFAULT NULL,
  `cdlan_cliente` varchar(80) DEFAULT NULL,
  `cdlan_commerciale` varchar(250) DEFAULT NULL,
  `cdlan_cod_termini_pag` varchar(250) DEFAULT NULL,
  `cdlan_note` text DEFAULT NULL,
  `cdlan_tipo_ord` enum('A','N','R') DEFAULT NULL,
  `cdlan_dur_rin` varchar(3) DEFAULT NULL,
  `cdlan_tacito_rin` varchar(2) DEFAULT NULL,
  `cdlan_sost_ord` varchar(150) DEFAULT NULL,
  `cdlan_tempi_ril` varchar(3) DEFAULT '0',
  `cdlan_durata_servizio` varchar(10) DEFAULT NULL,
  `cdlan_dataconferma` varchar(10) DEFAULT NULL,
  `cdlan_rif_ordcli` varchar(240) DEFAULT NULL,
  `cdlan_rif_tech_nom` varchar(240) DEFAULT NULL,
  `cdlan_rif_tech_tel` varchar(250) DEFAULT NULL,
  `cdlan_rif_tech_email` varchar(240) DEFAULT NULL,
  `cdlan_rif_altro_tech_nom` varchar(240) DEFAULT NULL,
  `cdlan_rif_altro_tech_tel` varchar(240) DEFAULT NULL,
  `cdlan_rif_altro_tech_email` varchar(240) DEFAULT NULL,
  `cdlan_rif_adm_nom` varchar(240) DEFAULT NULL,
  `cdlan_rif_adm_tech_tel` varchar(240) DEFAULT NULL,
  `cdlan_rif_adm_tech_email` varchar(240) DEFAULT NULL,
  `cdlan_int_fatturazione` enum('1','2','3','4','6','12') DEFAULT NULL,
  `cdlan_int_fatturazione_att` enum('1','2') DEFAULT NULL,
  `cdlan_stato` varchar(50) NOT NULL DEFAULT 'BOZZA',
  `cdlan_evaso` int(10) DEFAULT 0,
  `cdlan_chiuso` int(10) DEFAULT 0,
  `cdlan_anno` varchar(4) DEFAULT NULL,
  `cdlan_valuta` varchar(4) DEFAULT 'EURO',
  `written_by` varchar(150) DEFAULT NULL,
  `profile_iva` varchar(45) DEFAULT NULL,
  `profile_cf` varchar(45) DEFAULT NULL,
  `profile_address` varchar(250) DEFAULT NULL,
  `profile_city` varchar(45) DEFAULT NULL,
  `profile_cap` varchar(50) DEFAULT NULL,
  `profile_pv` varchar(2) DEFAULT NULL,
  `profile_sdi` varchar(45) DEFAULT NULL,
  `profile_lang` varchar(2) DEFAULT 'it',
  `cdlan_cliente_id` int(10) DEFAULT NULL,
  `service_type` varchar(250) DEFAULT NULL,
  `data_decorrenza` varchar(10) DEFAULT NULL,
  `cdlan_tacito_rin_in_pdf` varchar(2) DEFAULT '1',
  `is_colo` varchar(50) DEFAULT '0',
  `origin_cod_termini_pag` varchar(250) DEFAULT NULL,
  `is_arxivar` int(1) DEFAULT 1,
  `from_cp` int(1) DEFAULT 0,
  `arx_doc_number` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1767 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci


CREATE TABLE `orders_rows` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orders_id` int(11) NOT NULL,
  `cdlan_systemodv_row` int(30) DEFAULT 0,
  `cdlan_codart` varchar(40) DEFAULT NULL,
  `cdlan_descart` text DEFAULT NULL,
  `cdlan_qta` varchar(20) DEFAULT '1',
  `cdlan_serialnumber` varchar(25) DEFAULT NULL,
  `cdlan_prezzo` varchar(20) DEFAULT '0',
  `cdlan_prezzo_attivazione` varchar(20) DEFAULT '0',
  `cdlan_prezzo_cessazione` varchar(20) DEFAULT '0',
  `cdlan_ragg_fatturazione` varchar(20) DEFAULT 'A',
  `cdlan_data_attivazione` varchar(10) DEFAULT NULL,
  `cdlan_codice_kit` varchar(72) DEFAULT NULL,
  `index_kit` int(5) DEFAULT 0,
  `note_tecnici` blob DEFAULT NULL,
  `data_annullamento` varchar(10) DEFAULT NULL,
  `confirm_data_attivazione` int(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `FK_orders_rows_orders` (`orders_id`),
  CONSTRAINT `FK_orders_rows_orders` FOREIGN KEY (`orders_id`) REFERENCES `orders` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7233 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci