// Code generated from apps/binocolo/docs/company-legend.html — DO NOT EDIT BY HAND.
// Regola (DEEP-DIVE-DECISIONS.md §1): le semantiche codice→voce vengono SOLO dalla
// legend del vendor, mai assegnate a mano — è la lezione del falso "quirk ROE"
// (IIC178 sono le imposte, non l'utile). Estrazione di riferimento:
// artifacts/claude/iic_legend_map.json (276 codici IIC + 3 refusi normalizzati).

package binocolo

// maCEELabels mappa il numero voce (famiglia normalizzata: IICxxx/IPLxxx/IICC351 →
// "xxx") all'etichetta ufficiale della legend. I tre refusi della legend emessi
// verbatim dall'API (IPL231, IPL232, IICC351) sono normalizzati a 231/232/351.
var maCEELabels = map[string]string{
	"001": "A. CREDITS TO SHAREHOLDERS",
	"002": "Credits to shareholders part of which is carried over",
	"003": "B.I.1. Startup/Expansions",
	"004": "B.I.2. Research and development",
	"005": "B.I.3. Patents",
	"006": "B.I.4. Permits and licenses",
	"007": "B.I.5. Goodwill",
	"008": "B.I.6. Assets under construction and payments in account",
	"009": "B.I.7. Others",
	"010": "Depreciation provisions intangible fixed assets",
	"011": "B.I. TOTAL INTANGIBLE FIXED ASSETS",
	"012": "B.II.1. Land and buildings",
	"013": "B.II.2. Plants and machinery",
	"014": "B.II.3.Industrial equipment",
	"015": "B.II.4. Other goods",
	"016": "B.II.5. Assets under construction and payments on account",
	"017": "Depreciation provisions tangible fixed assets",
	"018": "B.II. TOTAL TANGIBLE FIXED ASSETS",
	"019": "B.III.1.a. Participating interests in subsidiaries",
	"020": "B.III.1.b.Participating interests in affiliated companies",
	"021": "B.III.1.c. Participating interests in parent companies",
	"022": "B.III.1.d-bis. Participating interests in other companies",
	"023": "B.III.1. TOTAL PARTICIPATING INTERESTS",
	"024": "B.III.2.a. Credits to Subsidiaries",
	"025": "B.III.2.a. Credits to Subsidiaries due beyond the next financial year",
	"026": "B.III.2.b. Credits to affiliated companies",
	"027": "B.III.2.b. Credits to affiliated companies due beyond the next financial year",
	"028": "B.III.2.c. Credits to parent companies",
	"029": "B.III.2.c. Credits to parent companies due beyond the next financial year",
	"030": "B.III.2.d-bis. Credits to others",
	"031": "B.III.2.d-bis. Credits to others due beyond the next financial year",
	"032": "B.III.>> SHORT TERM FINANCIAL CREDITS",
	"033": "B.III.>> LONG TERM FINANCIAL CREDITS",
	"034": "B.III.2. TOTAL CREDITS FINANCIAL FIXED ASSETS",
	"035": "B.III.3. Other credities",
	"036": "B.III.4. Own shares",
	"037": "Own shares at their nominal value",
	"038": "B.III. TOTAL FINANCIAL FIXED ASSETS",
	"039": "B. TOTAL FIXED ASSETS",
	"040": "C.I.1. Ra materials",
	"041": "C.I.2. Semi-finished products and products in progress",
	"042": "C.I.3. Work in progress",
	"043": "C.I.4. Finished products",
	"044": "C.I.5. Payments on account",
	"045": "C.I. TOTAL INVENTORY",
	"046": "C.II.1. Credits to customers",
	"047": "C.II.1. Credits to customers due beyond the next financial year",
	"048": "C.II.2. Credits to subsidiaries",
	"049": "C.II.2. Credits to subsidiaries due beyond the next financial year",
	"050": "C.II.3. Credits to affiliated companies",
	"051": "C.II.3. Credits to affiliated companies due beyond the next financial year",
	"052": "C.II.4. Credits to parent companies",
	"053": "C.II.4. Credits to parent companies due beyond the next financial year",
	"054": "C.II.5. Credits to others",
	"055": "C.II.5. Credits to others due beyond the next financial year",
	"056": "C.II.>> SHORT TERM CREDITS",
	"057": "C.II.>> CREDITS DUE BEYOND THE NEXT FINANCIAL YEAR",
	"058": "C.II. TOTAL CREDITS",
	"059": "C.III.1. Participating interests in subsidiaries",
	"060": "C.III.2. Participating interests in affiliated companies",
	"061": "C.III.3. Participating interests in parent companies",
	"062": "C.III.4. Other participating interests",
	"063": "C.III.5. Own shares",
	"064": "Own shares at their nominal value",
	"065": "C.III.6. Other securities",
	"066": "C.III. TOTAL FINANCIAL ASSETS",
	"067": "C.IV.1. Bank deposits",
	"068": "C.IV.2. Cheques",
	"069": "C.IV.3. Cash in hand",
	"070": "C.IV. Cash equivalents",
	"071": "C. CURRENT ASSETS",
	"072": "D. Accruals and deferrals",
	"073": "Accruals and deferrals of which loan discounts",
	"074": "TOTAL ASSETS",
	"075": "A.I. Share capital",
	"076": "A.II. Share premium reserve",
	"077": "A.III. Revaluation reserve",
	"078": "A.IV. Legal reserve",
	"079": "A.VI. Reserve for own shares",
	"080": "A.V. Statutory reserve",
	"081": "A.VI. Other reserves",
	"082": "A.VIII. Profit/Loss carried forward",
	"083": "A.IX. Profit/Loss for the year",
	"084": "A. TOTAL NET WORTH",
	"085": "B.1. Pension fund",
	"086": "B.2. Tax fund",
	"087": "B.3. Other funds",
	"088": "B. TOTAL RISK PROVISIONS",
	"089": "C. Severance payments",
	"090": "D.1. Bonds",
	"091": "D.1. Bonds due beyond the next financial year",
	"092": "D.2. Convertible bonds",
	"093": "D.2. convertible bonds due beyond the next financial year",
	"094": "D.4. Debts owed to banks",
	"095": "D.4. Debts owed to banks due beyond the next financial year",
	"096": "D.5. Debts owed to other lenders",
	"097": "D.5. Debts owed to other lenders due beyond the next financial year",
	"098": "D.6. Account/Advances",
	"099": "D.6. Account/advances due beyond the next financial year",
	"100": "D.7. Debts owed to suppliers",
	"101": "D.7. Debts owed to suppliers due beyond the next financial year",
	"102": "D.8. Credit instruments",
	"103": "D.8. Credit instruments due beyond the next financial year",
	"104": "D.9. Debts owed to subsidiaries",
	"105": "D.9. Debts owed to subsidiaries due beyond the next financial year",
	"106": "D.10. Debts owed to affiliated companies",
	"107": "D.10. Debts owed to affiliated companies due beyond the next financial year",
	"108": "D.11. Debts owed to parent companies",
	"109": "D.11. Debts owed to parent companies due beyond the next financial year",
	"110": "D.12. Tax liabilities",
	"111": "D.12. Tax liabilities due beyond the next financial year",
	"112": "D.13. Debts owed to social security agencies",
	"113": "D.13. Debts owed to social security agencies due beyond the next financial year",
	"114": "D.14. Other debts",
	"115": "D.14. Other debts due beyond the next financial year",
	"116": "D.>> SHORT TERMS DEBTS",
	"117": "D.>> DEBTS DUE BEYOND THE NEXT FINANCIAL YEAR",
	"118": "D. TOTAL DEBTS",
	"119": "E. ACCRUALS AND DEFERRALS",
	"120": "Accruals and deferrals of which: premiums on loans",
	"121": "TOTAL LIABILITIES",
	"122": "TOTAL MEMORANDUM ACCOUNTS (**)",
	"123": "Memorandum accounts of which guarantees pledged",
	"124": "A.1. Revenues from sales and services",
	"125": "A.2. Product inventory variations",
	"126": "A.3. Work variations",
	"127": "A.4. Increases in fixed assets",
	"128": "A.5. Total other revenues",
	"129": "-- > other revenues of which contributions for operating expenses",
	"130": "A. TOTAL PRODUCTION VALUE",
	"131": "B.6. Purchase of materials",
	"132": "B.7. Services",
	"133": "B.8. Leased assets",
	"134": "B.9. A wages/salaries",
	"135": "B.9.b. Social security costs",
	"136": "B.9.c. Severance payments",
	"137": "B.9.d. Pensions",
	"138": "B.9.e. Other costs",
	"139": "B.9. TOT staff costs",
	"140": "B.10.a. Depreciation of intangibles",
	"141": "B.10.b. Depreciation of tangibles",
	"142": "B.10.c. Fixed asset impairment",
	"143": "B.10.d. Impairment of credits and disp.",
	"144": "B.10. TOT depreciation and impairment",
	"145": "B.11. Variation in materials",
	"146": "B.12. Risk provisions",
	"147": "B.13. Other provisions",
	"148": "B.14. Other operating charges",
	"149": "B. PRODUCTION COSTS",
	"150": "C.15. Revenues from participating interests",
	"151": "Of which in subsidiaries/affiliated companies",
	"152": "C.16.a. Revenues from credits financial fixed assets",
	"153": "Revenues from credits financial fixed assets of which in subsidiaries/affiliated",
	"154": "C.16.b. Revenues from fix securities",
	"155": "C.16.c. Revenues from current securities",
	"156": "C.16.d. Other revenues",
	"157": "Other revenues of which in subsidiaries/affiliated companies",
	"158": "C.16. Total other revenues",
	"159": "C.17. Total financial charges",
	"160": "Financial charges of which in subsidiaries/affiliated companies",
	"161": "C. TOTAL REVENUES AND FINANCIAL CHARGES",
	"162": "D.18.a. Appreciation of participating interests",
	"163": "D.18.b. Appreciation of other financial fixed assets",
	"164": "D.18.c. Appreciation of securities",
	"165": "D.18. Total appreciation",
	"166": "D.19.a. Impairment of participating interests",
	"167": "D.19.b. Impairment of other financial fixed assets",
	"168": "D.19.c. Impairment of securities",
	"169": "D.19. Total impairment",
	"170": "D. TOTAL VALUE ADJUSTMENTS TO FINANCIAL ASSETS AND LIABILITIES (*)",
	"171": "E.20. Extraordinary revenues",
	"172": "Extraordinary revenues of which capital gains",
	"173": "E.21. Ordinary charges",
	"174": "Ordinary charges of which capital losses",
	"175": "Ordinary charges of which taxes from previous financial year",
	"176": "E. TOTAL EXTRAORDINARY REVENUES AND CHARGES",
	"177": "Result before taxes",
	"178": "20. Total current, deferred and prepaid income tax",
	"179": "21. PROFIT/LOSS FOR THE YEAR",
	"180": "C.II.4.bis. Tax assets",
	"181": "C.II.4.bis. Tax assets due beyond the next financial year",
	"182": "C.II.5.ter. Credits for prepaid taxes",
	"183": "C.II.5.ter. Credits for prepaid taxes due beyond the next financial year",
	"184": "D.3. Debts owed to shareholders",
	"185": "D.3. Debts owed to shareholders due beyond the next financial year",
	"186": "A.2. + A.3. Total variations",
	"187": "B.9. c+d+e severance payments + pensions + other costs",
	"188": "B.10.a.+b.+c. Depreciation and impairment of fixed assets",
	"189": "C.16.b.+c. Revenues from securities",
	"190": "C.17.bis. Profit and loss from foreign-exchange",
	"191": "20.a. Current taxes",
	"192": "20.c. Deferred and prepaid tax",
	"193": "Credits to shareholders part of which is to reported",
	"194": "B.III.1.d. Equity investments controlled by parent companies",
	"195": "B.III.2.d. Receivables due from companies controlled by parent companies",
	"196": "B.III.2.d. Receivables due from companies controlled by parent companies due bey",
	"197": "B.III.4. Derivative active financial instruments",
	"198": "C.II.5. Receivables due from companies controlled by parent companies",
	"199": "C.II.5. Receivables due from companies controlled by parent companies due beyond",
	"200": "C.III.3.bis Investments in companies controlled by parent companies",
	"201": "C.III.5. Derivative active financial instruments",
	"202": "Financial assets for central pool management",
	"203": "Extraordinary reserve",
	"204": "Reserves from exceptions as per art. 2423 civil code",
	"205": "Shares reserve of the parent entity",
	"206": "Investment revaluation reserve",
	"207": "Contributions for capital increase",
	"208": "Contributions for future capital increase",
	"209": "Contributions to capital account",
	"210": "Contributions to cover losses",
	"211": "Capital reduction reserve",
	"212": "Merger surplus reserve",
	"213": "Reserve from exchange gains not redeemed",
	"214": "Miscellaneous other reserves",
	"215": "",
	"216": "Minimised loss for the year",
	"218": "A.X. Negative reserve for own portfolio shares",
	"219": "B.3. Passive derivative financial instruments",
	"220": "D.11.bis. Debts due to companies controlled by parent companies",
	"221": "D.11.bis. Debts due to companies controlled by parent companies due beyond the n",
	"223": "Other revenues",
	"224": "Difference between value and cost of production (a - b)",
	"225": "C.15. By subsidiary companies",
	"226": "C.15. By affiliated companies",
	"227": "C.15. By parent companies",
	"228": "C.15. Companies subjected to parent companies",
	"229": "C.15. Other",
	"230": "C.16.a. By subsidiary companies",
	"231": "C.16.a. By affiliated companies",
	"232": "C.16.a. By parent companies",
	"233": "C.16.a. Companies subjected to parent companies",
	"234": "C.16.a. Other",
	"235": "C.16.d. By subsidiary companies",
	"236": "C.16.d. By affiliated companies",
	"237": "C.16.d. By parent companies",
	"238": "C.16.d. Companies subjected to parent companies",
	"239": "C.16.d. Other",
	"240": "C.17. To subsidiary companies",
	"241": "C.17. To associated companies",
	"242": "C.17. To parent companies",
	"243": "C.17. To companies controlled by parent companies",
	"244": "C.17. To other",
	"245": "D.18.d. Derivative financial instruments",
	"246": "D.19.d. Derivative financial instruments",
	"250": "20.d. Income (expense) arising from the adoption of the fiscal consolidated syst",
	"316": "B.III.2.a. Total credits to Subsidiaries",
	"317": "B.III.2.b. Total credits to affiliated companies",
	"318": "B.III.2.c. Total credits to parent companies",
	"319": "B.III.2.d. Total receivables due from companies controlled by parent companies",
	"320": "B.III.2.d-bis. Total credits to others",
	"321": "C.II.1. Total credits to customers",
	"322": "C.II.2. Total credits to subsidiaries",
	"323": "C.II.3. Total credits to affiliated companies",
	"324": "C.II.4. Total credits to parent companies",
	"325": "C.II.5. Total receivables due from companies controlled by parent companies",
	"326": "C.II.4.bis. Total tax assets",
	"327": "C.II.5.ter. Total credits for prepaid taxes",
	"328": "C.II.5. Total credits to others",
	"329": "D.1. Total Bonds",
	"330": "D.2. Total convertible bonds",
	"331": "D.3. Total debts due to partners for financing",
	"332": "D.4. Totale debts owed to banks",
	"333": "D.5. Total debts due to other providers of finance",
	"334": "D.6. Total account/advances",
	"335": "D.7. Total trade debts",
	"336": "D.8. Total credit instruments",
	"337": "D.9. Total debts owed to subsidiary companies",
	"338": "D.10. Total debts owed to affiliated companies",
	"339": "D.11. Total debts due to parent companies",
	"340": "D.11.bis. Total debts due to companies controlled by parent companies",
	"341": "D.12. Total tax liabilities",
	"342": "D.13. Total debts due to social security and welfare institutions",
	"343": "D.14. Total other debts",
	"344": "Other financial fixed assets",
	"345": "Reserve from current profit adjustments",
	"347": "20.b. Tax related to previous years",
	"349": "Tangible fixed assets aimed at selling",
	"350": ".Financial assets for central pool management",
	"351": ".Financial assets for central pool management",
}
