-- estrae fatture non saldate o non in scadenziario
SELECT
    t.DO11_DITTA_CG18,
    t.DO11_NUMREG_CO99,
    t.DO11_DOCUM_MG36,
    d.MG36_DESCDOCUM,
    t.DO11_NUMDOC,
    t.DO11_SEZDOC,
    t.DO11_DATADOC,
    t.DO11_CLIFOR_CG44,
    t.DO11_NUMDOCORIG,
    t.DO11_NOTEDOCUM,
    po.PO_NUMNSDOC,
    po.PO_SEZNSDOC,
    po.PO_RIFNSDOC,
    po.PO_RIFVSDOC,
    po.PO_NUMREGRIF,
    tot.DO13_TOTDOCUMENTO,
    tot.DO13_TOTAPAGARE,
    s.EF01_NUMRATA,
    s.EF01_SCADE_S,
    s.EF01_IMPEFFORIG,
    ISNULL(s.EF01_IMPEFF_S, tot.DO13_TOTAPAGARE) AS RESIDUO,
    ISNULL(pag.PAGATO, 0) AS PAGATO,
    ISNULL(pag.ABBUONO, 0) AS ABBUONO,
    ISNULL(pag.ACCONTO, 0) AS ACCONTO,
    CASE
        WHEN s.EF01_NUMREG_CO99 IS NULL THEN 'NON IN SCADENZIARIO'
        ELSE 'NON SALDATA'
    END AS STATO
FROM dbo.DO11_DOCTESTATA AS t
INNER JOIN dbo.MG36_DOCUMENTI AS d
    ON d.MG36_CODDOCUM = t.DO11_DOCUM_MG36
LEFT JOIN dbo.DO13_DOCTOTALI AS tot
    ON tot.DO13_DITTA_CG18 = t.DO11_DITTA_CG18
   AND tot.DO13_NUMREG_CO99 = t.DO11_NUMREG_CO99
LEFT JOIN dbo.EF01_SCADENZE AS s
    ON s.EF01_DITTA_CG18 = t.DO11_DITTA_CG18
   AND s.EF01_NUMREG_CO99 = t.DO11_NUMREG_CO99
LEFT JOIN (
    SELECT
        EF06_DITTA_CG18, EF06_NUMREG_CO99,
        EF06_RIGACONT_EF01, EF06_PROGEC_EF01, EF06_PROGEFF_EF01,
        SUM(ISNULL(EF06_IMPMOVPAG, 0)) AS PAGATO,
        SUM(ISNULL(EF06_IMPMOVABB, 0)) AS ABBUONO,
        SUM(ISNULL(EF06_IMPMOVACC, 0)) AS ACCONTO
    FROM dbo.EF06_SCADSTO
    GROUP BY EF06_DITTA_CG18, EF06_NUMREG_CO99,
             EF06_RIGACONT_EF01, EF06_PROGEC_EF01, EF06_PROGEFF_EF01
) AS pag
    ON pag.EF06_DITTA_CG18 = s.EF01_DITTA_CG18
   AND pag.EF06_NUMREG_CO99 = s.EF01_NUMREG_CO99
   AND pag.EF06_RIGACONT_EF01 = s.EF01_RIGACONT_CG42
   AND pag.EF06_PROGEC_EF01 = s.EF01_PROGEC_EC01
   AND pag.EF06_PROGEFF_EF01 = s.EF01_PROGEFF
OUTER APPLY (
    SELECT
        STUFF((
            SELECT DISTINCT ', ' + CAST(r.DO12_NUMNSDOC AS varchar(20))
            FROM dbo.DO12_DOCTESTARIF AS r
            WHERE r.DO12_DITTA_CG18 = t.DO11_DITTA_CG18
              AND r.DO12_NUMREG_CO99 = t.DO11_NUMREG_CO99
              AND r.DO12_INDTIPODOC = 22
              AND ISNULL(r.DO12_NUMNSDOC, 0) <> 0
            FOR XML PATH(''), TYPE
        ).value('.', 'varchar(max)'), 1, 2, '') AS PO_NUMNSDOC,
        STUFF((
            SELECT DISTINCT ', ' + RTRIM(r.DO12_SEZNSDOC)
            FROM dbo.DO12_DOCTESTARIF AS r
            WHERE r.DO12_DITTA_CG18 = t.DO11_DITTA_CG18
              AND r.DO12_NUMREG_CO99 = t.DO11_NUMREG_CO99
              AND r.DO12_INDTIPODOC = 22
              AND NULLIF(RTRIM(r.DO12_SEZNSDOC), '') IS NOT NULL
            FOR XML PATH(''), TYPE
        ).value('.', 'varchar(max)'), 1, 2, '') AS PO_SEZNSDOC,
        STUFF((
            SELECT DISTINCT ', ' + RTRIM(r.DO12_RIFNSDOC)
            FROM dbo.DO12_DOCTESTARIF AS r
            WHERE r.DO12_DITTA_CG18 = t.DO11_DITTA_CG18
              AND r.DO12_NUMREG_CO99 = t.DO11_NUMREG_CO99
              AND NULLIF(RTRIM(r.DO12_RIFNSDOC), '') IS NOT NULL
            FOR XML PATH(''), TYPE
        ).value('.', 'varchar(max)'), 1, 2, '') AS PO_RIFNSDOC,
        STUFF((
            SELECT DISTINCT ', ' + RTRIM(r.DO12_RIFVSDOC)
            FROM dbo.DO12_DOCTESTARIF AS r
            WHERE r.DO12_DITTA_CG18 = t.DO11_DITTA_CG18
              AND r.DO12_NUMREG_CO99 = t.DO11_NUMREG_CO99
              AND NULLIF(RTRIM(r.DO12_RIFVSDOC), '') IS NOT NULL
              AND RTRIM(r.DO12_RIFVSDOC) <> '-'
            FOR XML PATH(''), TYPE
        ).value('.', 'varchar(max)'), 1, 2, '') AS PO_RIFVSDOC,
        STUFF((
            SELECT DISTINCT ', ' + RTRIM(cr.DO33_NUMREGRIF_CO99)
            FROM dbo.DO33_DOCCORPORIF AS cr
            WHERE cr.DO33_DITTA_CG18 = t.DO11_DITTA_CG18
              AND cr.DO33_NUMREG_CO99 = t.DO11_NUMREG_CO99
              AND cr.DO33_INDTIPODOC = 22
              AND cr.DO33_NUMREGRIF_CO99 IS NOT NULL
            FOR XML PATH(''), TYPE
        ).value('.', 'varchar(max)'), 1, 2, '') AS PO_NUMREGRIF
) AS po
WHERE d.MG36_INDCLIFOR = 2
  AND d.MG36_INDLISACQVEN = 1
  AND d.MG36_TIPODOC IN (3, 4, 5)
  AND t.DO11_DITTA_CG18 = 1
  AND t.DO11_ANNODOC = 2026
  AND (
        s.EF01_NUMREG_CO99 IS NULL
     OR (s.EF01_INDSTATO_S = 0 AND ABS(ISNULL(s.EF01_IMPEFF_S, 0)) > 0.02)
  )
ORDER BY t.DO11_DATADOC, t.DO11_NUMDOC;