// Code generated by cmd/generate; DO NOT EDIT.

package factorial

import (
	"encoding/json"
	"fmt"
)

// WebhookSubscriptionType identifies a Factorial webhook event.
type WebhookSubscriptionType string

const (
	WebhookAPIPublicWebhookSubscriptionCreate                                 WebhookSubscriptionType = "api_public/webhook_subscription/create"
	WebhookAPIPublicWebhookSubscriptionDelete                                 WebhookSubscriptionType = "api_public/webhook_subscription/delete"
	WebhookAPIPublicWebhookSubscriptionUpdate                                 WebhookSubscriptionType = "api_public/webhook_subscription/update"
	WebhookATSApplicationApply                                                WebhookSubscriptionType = "ats/application/apply"
	WebhookATSApplicationCreate                                               WebhookSubscriptionType = "ats/application/create"
	WebhookATSApplicationCreateFromEmployee                                   WebhookSubscriptionType = "ats/application/create_from_employee"
	WebhookATSApplicationDelete                                               WebhookSubscriptionType = "ats/application/delete"
	WebhookATSApplicationUpdate                                               WebhookSubscriptionType = "ats/application/update"
	WebhookATSCandidateCreate                                                 WebhookSubscriptionType = "ats/candidate/create"
	WebhookATSCandidateDelete                                                 WebhookSubscriptionType = "ats/candidate/delete"
	WebhookATSCandidateUpdate                                                 WebhookSubscriptionType = "ats/candidate/update"
	WebhookATSEvaluationFormSaveAsTemplate                                    WebhookSubscriptionType = "ats/evaluation_form/save_as_template"
	WebhookATSJobPostingCreate                                                WebhookSubscriptionType = "ats/job_posting/create"
	WebhookATSJobPostingDelete                                                WebhookSubscriptionType = "ats/job_posting/delete"
	WebhookATSJobPostingDuplicate                                             WebhookSubscriptionType = "ats/job_posting/duplicate"
	WebhookATSJobPostingUpdate                                                WebhookSubscriptionType = "ats/job_posting/update"
	WebhookAttendanceShiftAutofill                                            WebhookSubscriptionType = "attendance/shift/autofill"
	WebhookAttendanceShiftBreakEnd                                            WebhookSubscriptionType = "attendance/shift/break_end"
	WebhookAttendanceShiftBreakStart                                          WebhookSubscriptionType = "attendance/shift/break_start"
	WebhookAttendanceShiftClockIn                                             WebhookSubscriptionType = "attendance/shift/clock_in"
	WebhookAttendanceShiftClockOut                                            WebhookSubscriptionType = "attendance/shift/clock_out"
	WebhookAttendanceShiftCreate                                              WebhookSubscriptionType = "attendance/shift/create"
	WebhookAttendanceShiftDelete                                              WebhookSubscriptionType = "attendance/shift/delete"
	WebhookAttendanceShiftToggleClock                                         WebhookSubscriptionType = "attendance/shift/toggle_clock"
	WebhookAttendanceShiftUpdate                                              WebhookSubscriptionType = "attendance/shift/update"
	WebhookBankingBankAccountNumberUpsert                                     WebhookSubscriptionType = "banking/bank_account_number/upsert"
	WebhookBookkeepersManagementIncidenceUpdate                               WebhookSubscriptionType = "bookkeepers_management/incidence/update"
	WebhookCompaniesLegalEntityCreate                                         WebhookSubscriptionType = "companies/legal_entity/create"
	WebhookContractsContractVersionCreate                                     WebhookSubscriptionType = "contracts/contract_version/create"
	WebhookContractsContractVersionDelete                                     WebhookSubscriptionType = "contracts/contract_version/delete"
	WebhookContractsContractVersionUpdate                                     WebhookSubscriptionType = "contracts/contract_version/update"
	WebhookContractsContractVersionRequestApprove                             WebhookSubscriptionType = "contracts/contract_version_request/approve"
	WebhookContractsContractVersionRequestCreatePromoteRequest                WebhookSubscriptionType = "contracts/contract_version_request/create_promote_request"
	WebhookContractsContractVersionRequestDelete                              WebhookSubscriptionType = "contracts/contract_version_request/delete"
	WebhookContractsContractVersionRequestReject                              WebhookSubscriptionType = "contracts/contract_version_request/reject"
	WebhookCustomResourcesSchemaCreate                                        WebhookSubscriptionType = "custom_resources/schema/create"
	WebhookDocumentsDocumentBulkCreate                                        WebhookSubscriptionType = "documents/document/bulk_create"
	WebhookDocumentsDocumentCreate                                            WebhookSubscriptionType = "documents/document/create"
	WebhookDocumentsDocumentDelete                                            WebhookSubscriptionType = "documents/document/delete"
	WebhookDocumentsDocumentMoveToTrashBin                                    WebhookSubscriptionType = "documents/document/move_to_trash_bin"
	WebhookDocumentsDocumentRestoreFromTrashBin                               WebhookSubscriptionType = "documents/document/restore_from_trash_bin"
	WebhookDocumentsDocumentUpdate                                            WebhookSubscriptionType = "documents/document/update"
	WebhookDocumentsFolderCreate                                              WebhookSubscriptionType = "documents/folder/create"
	WebhookDocumentsFolderUpdate                                              WebhookSubscriptionType = "documents/folder/update"
	WebhookEmployeesEmployeeCreateWithContract                                WebhookSubscriptionType = "employees/employee/create_with_contract"
	WebhookEmployeesEmployeeInvite                                            WebhookSubscriptionType = "employees/employee/invite"
	WebhookEmployeesEmployeeSetRegularAccessStartDate                         WebhookSubscriptionType = "employees/employee/set_regular_access_start_date"
	WebhookEmployeesEmployeeTerminate                                         WebhookSubscriptionType = "employees/employee/terminate"
	WebhookEmployeesEmployeeUnterminate                                       WebhookSubscriptionType = "employees/employee/unterminate"
	WebhookEmployeesEmployeeUpdate                                            WebhookSubscriptionType = "employees/employee/update"
	WebhookExpensesExpensableBulkSetToPaid                                    WebhookSubscriptionType = "expenses/expensable/bulk_set_to_paid"
	WebhookExpensesExpensableUpdateReimbursableAmount                         WebhookSubscriptionType = "expenses/expensable/update_reimbursable_amount"
	WebhookFinanceCostCenterCreate                                            WebhookSubscriptionType = "finance/cost_center/create"
	WebhookFinanceCostCenterDelete                                            WebhookSubscriptionType = "finance/cost_center/delete"
	WebhookFinanceCostCenterEdit                                              WebhookSubscriptionType = "finance/cost_center/edit"
	WebhookLocationsLocationCreate                                            WebhookSubscriptionType = "locations/location/create"
	WebhookLocationsLocationDelete                                            WebhookSubscriptionType = "locations/location/delete"
	WebhookLocationsLocationUpdate                                            WebhookSubscriptionType = "locations/location/update"
	WebhookPayrollPolicyPeriodChangeStatus                                    WebhookSubscriptionType = "payroll/policy_period/change_status"
	WebhookPayrollSupplementCreate                                            WebhookSubscriptionType = "payroll/supplement/create"
	WebhookPayrollSupplementDelete                                            WebhookSubscriptionType = "payroll/supplement/delete"
	WebhookPayrollSupplementUpdate                                            WebhookSubscriptionType = "payroll/supplement/update"
	WebhookPayrollIntegrationsBaseCodeCreate                                  WebhookSubscriptionType = "payroll_integrations_base/code/create"
	WebhookPayrollIntegrationsBaseCodeDelete                                  WebhookSubscriptionType = "payroll_integrations_base/code/delete"
	WebhookPayrollIntegrationsBaseCodeUpdate                                  WebhookSubscriptionType = "payroll_integrations_base/code/update"
	WebhookPerformanceReviewProcessCreate                                     WebhookSubscriptionType = "performance/review_process/create"
	WebhookPerformanceReviewProcessCreateFromTemplate                         WebhookSubscriptionType = "performance/review_process/create_from_template"
	WebhookPerformanceReviewProcessDelete                                     WebhookSubscriptionType = "performance/review_process/delete"
	WebhookPerformanceReviewProcessDuplicate                                  WebhookSubscriptionType = "performance/review_process/duplicate"
	WebhookPerformanceReviewProcessRemindInBulk                               WebhookSubscriptionType = "performance/review_process/remind_in_bulk"
	WebhookPerformanceReviewProcessRemoveSchedule                             WebhookSubscriptionType = "performance/review_process/remove_schedule"
	WebhookPerformanceReviewProcessReopen                                     WebhookSubscriptionType = "performance/review_process/reopen"
	WebhookPerformanceReviewProcessSchedule                                   WebhookSubscriptionType = "performance/review_process/schedule"
	WebhookPerformanceReviewProcessStart                                      WebhookSubscriptionType = "performance/review_process/start"
	WebhookPerformanceReviewProcessStop                                       WebhookSubscriptionType = "performance/review_process/stop"
	WebhookPerformanceReviewProcessToggleArchive                              WebhookSubscriptionType = "performance/review_process/toggle_archive"
	WebhookPerformanceReviewProcessUpdateAgreementsConfiguration              WebhookSubscriptionType = "performance/review_process/update_agreements_configuration"
	WebhookPerformanceReviewProcessUpdateBasicInfo                            WebhookSubscriptionType = "performance/review_process/update_basic_info"
	WebhookPerformanceReviewProcessUpdateCompetenciesAssessmentsConfiguration WebhookSubscriptionType = "performance/review_process/update_competencies_assessments_configuration"
	WebhookPerformanceReviewProcessUpdateDeadline                             WebhookSubscriptionType = "performance/review_process/update_deadline"
	WebhookPerformanceReviewProcessUpdateEmployeeScoreConfiguration           WebhookSubscriptionType = "performance/review_process/update_employee_score_configuration"
	WebhookPerformanceReviewProcessUpdateReviewerStrategies                   WebhookSubscriptionType = "performance/review_process/update_reviewer_strategies"
	WebhookPerformanceReviewProcessUpdateSchedule                             WebhookSubscriptionType = "performance/review_process/update_schedule"
	WebhookPerformanceReviewProcessUpdateTargetStrategy                       WebhookSubscriptionType = "performance/review_process/update_target_strategy"
	WebhookShiftManagementShiftBulkCreate                                     WebhookSubscriptionType = "shift_management/shift/bulk_create"
	WebhookShiftManagementShiftBulkDelete                                     WebhookSubscriptionType = "shift_management/shift/bulk_delete"
	WebhookShiftManagementShiftCreate                                         WebhookSubscriptionType = "shift_management/shift/create"
	WebhookShiftManagementShiftDelete                                         WebhookSubscriptionType = "shift_management/shift/delete"
	WebhookTasksTaskBulkCreate                                                WebhookSubscriptionType = "tasks/task/bulk_create"
	WebhookTasksTaskBulkDelete                                                WebhookSubscriptionType = "tasks/task/bulk_delete"
	WebhookTasksTaskBulkUpdate                                                WebhookSubscriptionType = "tasks/task/bulk_update"
	WebhookTasksTaskCopy                                                      WebhookSubscriptionType = "tasks/task/copy"
	WebhookTasksTaskCreate                                                    WebhookSubscriptionType = "tasks/task/create"
	WebhookTasksTaskCreateComment                                             WebhookSubscriptionType = "tasks/task/create_comment"
	WebhookTasksTaskDelete                                                    WebhookSubscriptionType = "tasks/task/delete"
	WebhookTasksTaskUpdate                                                    WebhookSubscriptionType = "tasks/task/update"
	WebhookTeamsMembershipBulkUpsert                                          WebhookSubscriptionType = "teams/membership/bulk_upsert"
	WebhookTeamsMembershipCreate                                              WebhookSubscriptionType = "teams/membership/create"
	WebhookTeamsMembershipDelete                                              WebhookSubscriptionType = "teams/membership/delete"
	WebhookTeamsMembershipUpdate                                              WebhookSubscriptionType = "teams/membership/update"
	WebhookTeamsTeamCreate                                                    WebhookSubscriptionType = "teams/team/create"
	WebhookTeamsTeamDelete                                                    WebhookSubscriptionType = "teams/team/delete"
	WebhookTeamsTeamProject                                                   WebhookSubscriptionType = "teams/team/project"
	WebhookTeamsTeamUpdate                                                    WebhookSubscriptionType = "teams/team/update"
	WebhookTimeoffBlockedPeriodCreate                                         WebhookSubscriptionType = "timeoff/blocked_period/create"
	WebhookTimeoffBlockedPeriodDelete                                         WebhookSubscriptionType = "timeoff/blocked_period/delete"
	WebhookTimeoffBlockedPeriodUpdate                                         WebhookSubscriptionType = "timeoff/blocked_period/update"
	WebhookTimeoffLeaveApprove                                                WebhookSubscriptionType = "timeoff/leave/approve"
	WebhookTimeoffLeaveCreate                                                 WebhookSubscriptionType = "timeoff/leave/create"
	WebhookTimeoffLeaveDelete                                                 WebhookSubscriptionType = "timeoff/leave/delete"
	WebhookTimeoffLeaveReject                                                 WebhookSubscriptionType = "timeoff/leave/reject"
	WebhookTimeoffLeaveUpdate                                                 WebhookSubscriptionType = "timeoff/leave/update"
	WebhookTimeoffLeaveTypeCreate                                             WebhookSubscriptionType = "timeoff/leave_type/create"
	WebhookTimeoffLeaveTypeUpdate                                             WebhookSubscriptionType = "timeoff/leave_type/update"
	WebhookTimeoffPolicyCreate                                                WebhookSubscriptionType = "timeoff/policy/create"
	WebhookTimeoffPolicyDelete                                                WebhookSubscriptionType = "timeoff/policy/delete"
	WebhookTimeoffPolicyUpdate                                                WebhookSubscriptionType = "timeoff/policy/update"
	WebhookTrainingsCategoryCreate                                            WebhookSubscriptionType = "trainings/category/create"
	WebhookTrainingsCategoryDelete                                            WebhookSubscriptionType = "trainings/category/delete"
	WebhookTrainingsTrainingBulkDelete                                        WebhookSubscriptionType = "trainings/training/bulk_delete"
	WebhookTrainingsTrainingBulkUpdateCatalog                                 WebhookSubscriptionType = "trainings/training/bulk_update_catalog"
	WebhookTrainingsTrainingCreate                                            WebhookSubscriptionType = "trainings/training/create"
	WebhookTrainingsTrainingDelete                                            WebhookSubscriptionType = "trainings/training/delete"
	WebhookTrainingsTrainingUpdate                                            WebhookSubscriptionType = "trainings/training/update"
	WebhookTrainingsTrainingUpdateStatus                                      WebhookSubscriptionType = "trainings/training/update_status"
	WebhookWorkScheduleScheduleCreate                                         WebhookSubscriptionType = "work_schedule/schedule/create"
	WebhookWorkScheduleScheduleToggleArchive                                  WebhookSubscriptionType = "work_schedule/schedule/toggle_archive"
	WebhookWorkScheduleScheduleUpdate                                         WebhookSubscriptionType = "work_schedule/schedule/update"
)

// WebhookEvent pairs a subscription type with its payload schema type name.
type WebhookEvent struct {
	SubscriptionType WebhookSubscriptionType
	PayloadSchema    string // the Go type name ParseWebhook unmarshals into
}

// WebhookCatalog lists every webhook event in the spec (128 entries).
var WebhookCatalog = []WebhookEvent{
	{SubscriptionType: WebhookAPIPublicWebhookSubscriptionCreate, PayloadSchema: "APIPublicWebhookSubscription"},
	{SubscriptionType: WebhookAPIPublicWebhookSubscriptionDelete, PayloadSchema: "APIPublicWebhookSubscription"},
	{SubscriptionType: WebhookAPIPublicWebhookSubscriptionUpdate, PayloadSchema: "APIPublicWebhookSubscription"},
	{SubscriptionType: WebhookATSApplicationApply, PayloadSchema: "ATSApplication"},
	{SubscriptionType: WebhookATSApplicationCreate, PayloadSchema: "ATSApplication"},
	{SubscriptionType: WebhookATSApplicationCreateFromEmployee, PayloadSchema: "ATSApplication"},
	{SubscriptionType: WebhookATSApplicationDelete, PayloadSchema: "ATSApplication"},
	{SubscriptionType: WebhookATSApplicationUpdate, PayloadSchema: "ATSApplication"},
	{SubscriptionType: WebhookATSCandidateCreate, PayloadSchema: "ATSCandidate"},
	{SubscriptionType: WebhookATSCandidateDelete, PayloadSchema: "ATSCandidate"},
	{SubscriptionType: WebhookATSCandidateUpdate, PayloadSchema: "ATSCandidate"},
	{SubscriptionType: WebhookATSEvaluationFormSaveAsTemplate, PayloadSchema: "ATSEvaluationForm"},
	{SubscriptionType: WebhookATSJobPostingCreate, PayloadSchema: "ATSJobPosting"},
	{SubscriptionType: WebhookATSJobPostingDelete, PayloadSchema: "ATSJobPosting"},
	{SubscriptionType: WebhookATSJobPostingDuplicate, PayloadSchema: "ATSJobPosting"},
	{SubscriptionType: WebhookATSJobPostingUpdate, PayloadSchema: "ATSJobPosting"},
	{SubscriptionType: WebhookAttendanceShiftAutofill, PayloadSchema: "AttendanceShift"},
	{SubscriptionType: WebhookAttendanceShiftBreakEnd, PayloadSchema: "AttendanceShift"},
	{SubscriptionType: WebhookAttendanceShiftBreakStart, PayloadSchema: "AttendanceShift"},
	{SubscriptionType: WebhookAttendanceShiftClockIn, PayloadSchema: "AttendanceShift"},
	{SubscriptionType: WebhookAttendanceShiftClockOut, PayloadSchema: "AttendanceShift"},
	{SubscriptionType: WebhookAttendanceShiftCreate, PayloadSchema: "AttendanceShift"},
	{SubscriptionType: WebhookAttendanceShiftDelete, PayloadSchema: "AttendanceShift"},
	{SubscriptionType: WebhookAttendanceShiftToggleClock, PayloadSchema: "AttendanceShift"},
	{SubscriptionType: WebhookAttendanceShiftUpdate, PayloadSchema: "AttendanceShift"},
	{SubscriptionType: WebhookBankingBankAccountNumberUpsert, PayloadSchema: "BankingBankAccountNumber"},
	{SubscriptionType: WebhookBookkeepersManagementIncidenceUpdate, PayloadSchema: "BookkeepersManagementIncidence"},
	{SubscriptionType: WebhookCompaniesLegalEntityCreate, PayloadSchema: "CompaniesLegalEntity"},
	{SubscriptionType: WebhookContractsContractVersionCreate, PayloadSchema: "ContractsContractVersion"},
	{SubscriptionType: WebhookContractsContractVersionDelete, PayloadSchema: "ContractsContractVersion"},
	{SubscriptionType: WebhookContractsContractVersionUpdate, PayloadSchema: "ContractsContractVersion"},
	{SubscriptionType: WebhookContractsContractVersionRequestApprove, PayloadSchema: "ContractsContractVersionRequest"},
	{SubscriptionType: WebhookContractsContractVersionRequestCreatePromoteRequest, PayloadSchema: "ContractsContractVersionRequest"},
	{SubscriptionType: WebhookContractsContractVersionRequestDelete, PayloadSchema: "ContractsContractVersionRequest"},
	{SubscriptionType: WebhookContractsContractVersionRequestReject, PayloadSchema: "ContractsContractVersionRequest"},
	{SubscriptionType: WebhookCustomResourcesSchemaCreate, PayloadSchema: "CustomResourcesSchema"},
	{SubscriptionType: WebhookDocumentsDocumentBulkCreate, PayloadSchema: "DocumentsDocument"},
	{SubscriptionType: WebhookDocumentsDocumentCreate, PayloadSchema: "DocumentsDocument"},
	{SubscriptionType: WebhookDocumentsDocumentDelete, PayloadSchema: "DocumentsDocument"},
	{SubscriptionType: WebhookDocumentsDocumentMoveToTrashBin, PayloadSchema: "DocumentsDocument"},
	{SubscriptionType: WebhookDocumentsDocumentRestoreFromTrashBin, PayloadSchema: "DocumentsDocument"},
	{SubscriptionType: WebhookDocumentsDocumentUpdate, PayloadSchema: "DocumentsDocument"},
	{SubscriptionType: WebhookDocumentsFolderCreate, PayloadSchema: "DocumentsFolder"},
	{SubscriptionType: WebhookDocumentsFolderUpdate, PayloadSchema: "DocumentsFolder"},
	{SubscriptionType: WebhookEmployeesEmployeeCreateWithContract, PayloadSchema: "EmployeesEmployee"},
	{SubscriptionType: WebhookEmployeesEmployeeInvite, PayloadSchema: "EmployeesEmployee"},
	{SubscriptionType: WebhookEmployeesEmployeeSetRegularAccessStartDate, PayloadSchema: "EmployeesEmployee"},
	{SubscriptionType: WebhookEmployeesEmployeeTerminate, PayloadSchema: "EmployeesEmployee"},
	{SubscriptionType: WebhookEmployeesEmployeeUnterminate, PayloadSchema: "EmployeesEmployee"},
	{SubscriptionType: WebhookEmployeesEmployeeUpdate, PayloadSchema: "EmployeesEmployee"},
	{SubscriptionType: WebhookExpensesExpensableBulkSetToPaid, PayloadSchema: "ExpensesExpensable"},
	{SubscriptionType: WebhookExpensesExpensableUpdateReimbursableAmount, PayloadSchema: "ExpensesExpensable"},
	{SubscriptionType: WebhookFinanceCostCenterCreate, PayloadSchema: "FinanceCostCenter"},
	{SubscriptionType: WebhookFinanceCostCenterDelete, PayloadSchema: "FinanceCostCenter"},
	{SubscriptionType: WebhookFinanceCostCenterEdit, PayloadSchema: "FinanceCostCenter"},
	{SubscriptionType: WebhookLocationsLocationCreate, PayloadSchema: "LocationsLocation"},
	{SubscriptionType: WebhookLocationsLocationDelete, PayloadSchema: "LocationsLocation"},
	{SubscriptionType: WebhookLocationsLocationUpdate, PayloadSchema: "LocationsLocation"},
	{SubscriptionType: WebhookPayrollPolicyPeriodChangeStatus, PayloadSchema: "PayrollPolicyPeriod"},
	{SubscriptionType: WebhookPayrollSupplementCreate, PayloadSchema: "PayrollSupplement"},
	{SubscriptionType: WebhookPayrollSupplementDelete, PayloadSchema: "PayrollSupplement"},
	{SubscriptionType: WebhookPayrollSupplementUpdate, PayloadSchema: "PayrollSupplement"},
	{SubscriptionType: WebhookPayrollIntegrationsBaseCodeCreate, PayloadSchema: "PayrollIntegrationsBaseCode"},
	{SubscriptionType: WebhookPayrollIntegrationsBaseCodeDelete, PayloadSchema: "PayrollIntegrationsBaseCode"},
	{SubscriptionType: WebhookPayrollIntegrationsBaseCodeUpdate, PayloadSchema: "PayrollIntegrationsBaseCode"},
	{SubscriptionType: WebhookPerformanceReviewProcessCreate, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessCreateFromTemplate, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessDelete, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessDuplicate, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessRemindInBulk, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessRemoveSchedule, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessReopen, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessSchedule, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessStart, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessStop, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessToggleArchive, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessUpdateAgreementsConfiguration, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessUpdateBasicInfo, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessUpdateCompetenciesAssessmentsConfiguration, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessUpdateDeadline, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessUpdateEmployeeScoreConfiguration, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessUpdateReviewerStrategies, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessUpdateSchedule, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookPerformanceReviewProcessUpdateTargetStrategy, PayloadSchema: "PerformanceReviewProcess"},
	{SubscriptionType: WebhookShiftManagementShiftBulkCreate, PayloadSchema: "ShiftManagementShift"},
	{SubscriptionType: WebhookShiftManagementShiftBulkDelete, PayloadSchema: "ShiftManagementShift"},
	{SubscriptionType: WebhookShiftManagementShiftCreate, PayloadSchema: "ShiftManagementShift"},
	{SubscriptionType: WebhookShiftManagementShiftDelete, PayloadSchema: "ShiftManagementShift"},
	{SubscriptionType: WebhookTasksTaskBulkCreate, PayloadSchema: "TasksTask"},
	{SubscriptionType: WebhookTasksTaskBulkDelete, PayloadSchema: "TasksTask"},
	{SubscriptionType: WebhookTasksTaskBulkUpdate, PayloadSchema: "TasksTask"},
	{SubscriptionType: WebhookTasksTaskCopy, PayloadSchema: "TasksTask"},
	{SubscriptionType: WebhookTasksTaskCreate, PayloadSchema: "TasksTask"},
	{SubscriptionType: WebhookTasksTaskCreateComment, PayloadSchema: "TasksTask"},
	{SubscriptionType: WebhookTasksTaskDelete, PayloadSchema: "TasksTask"},
	{SubscriptionType: WebhookTasksTaskUpdate, PayloadSchema: "TasksTask"},
	{SubscriptionType: WebhookTeamsMembershipBulkUpsert, PayloadSchema: "TeamsMembership"},
	{SubscriptionType: WebhookTeamsMembershipCreate, PayloadSchema: "TeamsMembership"},
	{SubscriptionType: WebhookTeamsMembershipDelete, PayloadSchema: "TeamsMembership"},
	{SubscriptionType: WebhookTeamsMembershipUpdate, PayloadSchema: "TeamsMembership"},
	{SubscriptionType: WebhookTeamsTeamCreate, PayloadSchema: "TeamsTeam"},
	{SubscriptionType: WebhookTeamsTeamDelete, PayloadSchema: "TeamsTeam"},
	{SubscriptionType: WebhookTeamsTeamProject, PayloadSchema: "TeamsTeam"},
	{SubscriptionType: WebhookTeamsTeamUpdate, PayloadSchema: "TeamsTeam"},
	{SubscriptionType: WebhookTimeoffBlockedPeriodCreate, PayloadSchema: "TimeoffBlockedPeriodsPolicy"},
	{SubscriptionType: WebhookTimeoffBlockedPeriodDelete, PayloadSchema: "TimeoffBlockedPeriodsPolicy"},
	{SubscriptionType: WebhookTimeoffBlockedPeriodUpdate, PayloadSchema: "TimeoffBlockedPeriodsPolicy"},
	{SubscriptionType: WebhookTimeoffLeaveApprove, PayloadSchema: "TimeoffLeave"},
	{SubscriptionType: WebhookTimeoffLeaveCreate, PayloadSchema: "TimeoffLeave"},
	{SubscriptionType: WebhookTimeoffLeaveDelete, PayloadSchema: "TimeoffLeave"},
	{SubscriptionType: WebhookTimeoffLeaveReject, PayloadSchema: "TimeoffLeave"},
	{SubscriptionType: WebhookTimeoffLeaveUpdate, PayloadSchema: "TimeoffLeave"},
	{SubscriptionType: WebhookTimeoffLeaveTypeCreate, PayloadSchema: "TimeoffLeaveType"},
	{SubscriptionType: WebhookTimeoffLeaveTypeUpdate, PayloadSchema: "TimeoffLeaveType"},
	{SubscriptionType: WebhookTimeoffPolicyCreate, PayloadSchema: "TimeoffPolicy"},
	{SubscriptionType: WebhookTimeoffPolicyDelete, PayloadSchema: "TimeoffPolicy"},
	{SubscriptionType: WebhookTimeoffPolicyUpdate, PayloadSchema: "TimeoffPolicy"},
	{SubscriptionType: WebhookTrainingsCategoryCreate, PayloadSchema: "TrainingsCategory"},
	{SubscriptionType: WebhookTrainingsCategoryDelete, PayloadSchema: "TrainingsCategory"},
	{SubscriptionType: WebhookTrainingsTrainingBulkDelete, PayloadSchema: "TrainingsTraining"},
	{SubscriptionType: WebhookTrainingsTrainingBulkUpdateCatalog, PayloadSchema: "TrainingsTraining"},
	{SubscriptionType: WebhookTrainingsTrainingCreate, PayloadSchema: "TrainingsTraining"},
	{SubscriptionType: WebhookTrainingsTrainingDelete, PayloadSchema: "TrainingsTraining"},
	{SubscriptionType: WebhookTrainingsTrainingUpdate, PayloadSchema: "TrainingsTraining"},
	{SubscriptionType: WebhookTrainingsTrainingUpdateStatus, PayloadSchema: "TrainingsTraining"},
	{SubscriptionType: WebhookWorkScheduleScheduleCreate, PayloadSchema: "WorkScheduleSchedule"},
	{SubscriptionType: WebhookWorkScheduleScheduleToggleArchive, PayloadSchema: "WorkScheduleSchedule"},
	{SubscriptionType: WebhookWorkScheduleScheduleUpdate, PayloadSchema: "WorkScheduleSchedule"},
}

// ParseWebhook unmarshals a webhook payload for the given subscription type into
// the correct typed struct pointer. It returns an error for an unknown type.
// Delivery note: Factorial POSTs the resource object at the TOP LEVEL (no
// {type,data} envelope); the challenge is echoed via the x-factorial-wh-challenge
// header (handled by your HTTP handler, not here).
func ParseWebhook(subscriptionType string, body []byte) (any, error) {
	switch WebhookSubscriptionType(subscriptionType) {
	case WebhookAPIPublicWebhookSubscriptionCreate:
		var p APIPublicWebhookSubscription
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAPIPublicWebhookSubscriptionDelete:
		var p APIPublicWebhookSubscription
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAPIPublicWebhookSubscriptionUpdate:
		var p APIPublicWebhookSubscription
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSApplicationApply:
		var p ATSApplication
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSApplicationCreate:
		var p ATSApplication
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSApplicationCreateFromEmployee:
		var p ATSApplication
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSApplicationDelete:
		var p ATSApplication
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSApplicationUpdate:
		var p ATSApplication
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSCandidateCreate:
		var p ATSCandidate
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSCandidateDelete:
		var p ATSCandidate
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSCandidateUpdate:
		var p ATSCandidate
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSEvaluationFormSaveAsTemplate:
		var p ATSEvaluationForm
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSJobPostingCreate:
		var p ATSJobPosting
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSJobPostingDelete:
		var p ATSJobPosting
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSJobPostingDuplicate:
		var p ATSJobPosting
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookATSJobPostingUpdate:
		var p ATSJobPosting
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAttendanceShiftAutofill:
		var p AttendanceShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAttendanceShiftBreakEnd:
		var p AttendanceShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAttendanceShiftBreakStart:
		var p AttendanceShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAttendanceShiftClockIn:
		var p AttendanceShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAttendanceShiftClockOut:
		var p AttendanceShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAttendanceShiftCreate:
		var p AttendanceShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAttendanceShiftDelete:
		var p AttendanceShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAttendanceShiftToggleClock:
		var p AttendanceShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookAttendanceShiftUpdate:
		var p AttendanceShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookBankingBankAccountNumberUpsert:
		var p BankingBankAccountNumber
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookBookkeepersManagementIncidenceUpdate:
		var p BookkeepersManagementIncidence
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookCompaniesLegalEntityCreate:
		var p CompaniesLegalEntity
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookContractsContractVersionCreate:
		var p ContractsContractVersion
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookContractsContractVersionDelete:
		var p ContractsContractVersion
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookContractsContractVersionUpdate:
		var p ContractsContractVersion
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookContractsContractVersionRequestApprove:
		var p ContractsContractVersionRequest
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookContractsContractVersionRequestCreatePromoteRequest:
		var p ContractsContractVersionRequest
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookContractsContractVersionRequestDelete:
		var p ContractsContractVersionRequest
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookContractsContractVersionRequestReject:
		var p ContractsContractVersionRequest
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookCustomResourcesSchemaCreate:
		var p CustomResourcesSchema
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookDocumentsDocumentBulkCreate:
		var p DocumentsDocument
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookDocumentsDocumentCreate:
		var p DocumentsDocument
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookDocumentsDocumentDelete:
		var p DocumentsDocument
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookDocumentsDocumentMoveToTrashBin:
		var p DocumentsDocument
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookDocumentsDocumentRestoreFromTrashBin:
		var p DocumentsDocument
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookDocumentsDocumentUpdate:
		var p DocumentsDocument
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookDocumentsFolderCreate:
		var p DocumentsFolder
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookDocumentsFolderUpdate:
		var p DocumentsFolder
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookEmployeesEmployeeCreateWithContract:
		var p EmployeesEmployee
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookEmployeesEmployeeInvite:
		var p EmployeesEmployee
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookEmployeesEmployeeSetRegularAccessStartDate:
		var p EmployeesEmployee
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookEmployeesEmployeeTerminate:
		var p EmployeesEmployee
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookEmployeesEmployeeUnterminate:
		var p EmployeesEmployee
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookEmployeesEmployeeUpdate:
		var p EmployeesEmployee
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookExpensesExpensableBulkSetToPaid:
		var p ExpensesExpensable
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookExpensesExpensableUpdateReimbursableAmount:
		var p ExpensesExpensable
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookFinanceCostCenterCreate:
		var p FinanceCostCenter
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookFinanceCostCenterDelete:
		var p FinanceCostCenter
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookFinanceCostCenterEdit:
		var p FinanceCostCenter
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookLocationsLocationCreate:
		var p LocationsLocation
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookLocationsLocationDelete:
		var p LocationsLocation
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookLocationsLocationUpdate:
		var p LocationsLocation
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPayrollPolicyPeriodChangeStatus:
		var p PayrollPolicyPeriod
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPayrollSupplementCreate:
		var p PayrollSupplement
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPayrollSupplementDelete:
		var p PayrollSupplement
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPayrollSupplementUpdate:
		var p PayrollSupplement
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPayrollIntegrationsBaseCodeCreate:
		var p PayrollIntegrationsBaseCode
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPayrollIntegrationsBaseCodeDelete:
		var p PayrollIntegrationsBaseCode
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPayrollIntegrationsBaseCodeUpdate:
		var p PayrollIntegrationsBaseCode
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessCreate:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessCreateFromTemplate:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessDelete:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessDuplicate:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessRemindInBulk:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessRemoveSchedule:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessReopen:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessSchedule:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessStart:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessStop:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessToggleArchive:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessUpdateAgreementsConfiguration:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessUpdateBasicInfo:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessUpdateCompetenciesAssessmentsConfiguration:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessUpdateDeadline:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessUpdateEmployeeScoreConfiguration:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessUpdateReviewerStrategies:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessUpdateSchedule:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookPerformanceReviewProcessUpdateTargetStrategy:
		var p PerformanceReviewProcess
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookShiftManagementShiftBulkCreate:
		var p ShiftManagementShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookShiftManagementShiftBulkDelete:
		var p ShiftManagementShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookShiftManagementShiftCreate:
		var p ShiftManagementShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookShiftManagementShiftDelete:
		var p ShiftManagementShift
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTasksTaskBulkCreate:
		var p TasksTask
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTasksTaskBulkDelete:
		var p TasksTask
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTasksTaskBulkUpdate:
		var p TasksTask
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTasksTaskCopy:
		var p TasksTask
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTasksTaskCreate:
		var p TasksTask
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTasksTaskCreateComment:
		var p TasksTask
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTasksTaskDelete:
		var p TasksTask
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTasksTaskUpdate:
		var p TasksTask
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTeamsMembershipBulkUpsert:
		var p TeamsMembership
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTeamsMembershipCreate:
		var p TeamsMembership
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTeamsMembershipDelete:
		var p TeamsMembership
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTeamsMembershipUpdate:
		var p TeamsMembership
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTeamsTeamCreate:
		var p TeamsTeam
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTeamsTeamDelete:
		var p TeamsTeam
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTeamsTeamProject:
		var p TeamsTeam
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTeamsTeamUpdate:
		var p TeamsTeam
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffBlockedPeriodCreate:
		var p TimeoffBlockedPeriodsPolicy
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffBlockedPeriodDelete:
		var p TimeoffBlockedPeriodsPolicy
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffBlockedPeriodUpdate:
		var p TimeoffBlockedPeriodsPolicy
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffLeaveApprove:
		var p TimeoffLeave
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffLeaveCreate:
		var p TimeoffLeave
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffLeaveDelete:
		var p TimeoffLeave
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffLeaveReject:
		var p TimeoffLeave
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffLeaveUpdate:
		var p TimeoffLeave
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffLeaveTypeCreate:
		var p TimeoffLeaveType
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffLeaveTypeUpdate:
		var p TimeoffLeaveType
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffPolicyCreate:
		var p TimeoffPolicy
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffPolicyDelete:
		var p TimeoffPolicy
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTimeoffPolicyUpdate:
		var p TimeoffPolicy
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTrainingsCategoryCreate:
		var p TrainingsCategory
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTrainingsCategoryDelete:
		var p TrainingsCategory
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTrainingsTrainingBulkDelete:
		var p TrainingsTraining
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTrainingsTrainingBulkUpdateCatalog:
		var p TrainingsTraining
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTrainingsTrainingCreate:
		var p TrainingsTraining
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTrainingsTrainingDelete:
		var p TrainingsTraining
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTrainingsTrainingUpdate:
		var p TrainingsTraining
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookTrainingsTrainingUpdateStatus:
		var p TrainingsTraining
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookWorkScheduleScheduleCreate:
		var p WorkScheduleSchedule
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookWorkScheduleScheduleToggleArchive:
		var p WorkScheduleSchedule
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	case WebhookWorkScheduleScheduleUpdate:
		var p WorkScheduleSchedule
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, fmt.Errorf("factorial: decoding webhook payload: %w", err)
		}
		return &p, nil
	default:
		return nil, fmt.Errorf("factorial: unknown webhook subscription type %q", subscriptionType)
	}
}
